### ISSUE TITLE
Domain doesn't work

### ISSUE THREAD

**Issue by ghost** [tungsten-client/documentation#5]
https://tungsten-client.github.io redirects to https://docs.tungstenclient.com, causing a "this site redirected you too many times" error.

What's likely happening is the domain is pointing/redirecting to the pages site rather than inheriting whatever gets released on the domain

**Comment by ghost** [comment]
https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/

**Comment by ghost** [comment]
https://hossainkhan.medium.com/using-custom-domain-for-github-pages-86b303d3918a

**Comment by HyperCodec** [comment]
fixed
